SELECT * FROM EMPLOYEES; --107
SELECT * FROM DEPARTMENTS; --27

SELECT COUNT(*) FROM EMPLOYEES, DEPARTMENTS; 


---MOSTRAR TODOS LOS EMPLEADOS QUE TENGAN UN DEPARTAMENTO ASIGNADO
SELECT * 
FROM    EMPLOYEES A, 
        DEPARTMENTS B
WHERE   A.DEPARTMENT_ID = B.DEPARTMENT_ID; 

SELECT *
FROM EMPLOYEES A
INNER JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID;


--MOSTRAR TODOS LOS EMPLEADOS, INDEPENDIENTEMENTE DE SI TIENEN UN DEPARTAMENTO ASIGNADO
SELECT *
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID;


--LEFT JOIN USANDO PRODUCTOS CARTESIANOS
SELECT *
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID (+); -- LEFT JOIN


-- MOSTRAR TODOS LOS DEPARTAMENTOS, INDEPENDIENTEMENTE DE SI TIENEN EMPLEADOS ASIGNADOS
SELECT *
FROM EMPLOYEES A
RIGHT JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID;

-- REPRESENTACIÓN CON PRODUCTOS CARTESIANOS Y WHERE
SELECT *
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID (+) = B.DEPARTMENT_ID; -- RIGHT JOIN


--MOSTRAR TODOS LOS EMPLEADOS QUE NO TENGAN UN DEPARTAMENTO ASIGNADO

SELECT A.* 
FROM EMPLOYEES A 
LEFT JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
WHERE B.DEPARTMENT_ID IS NULL;

--NOTACION DE PRODUCTOS CARTESIANOS
SELECT *
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID (+)
AND B.DEPARTMENT_ID IS NULL;

--MOSTRAR TODOS LOS DEPARTAMENTOS QUE NO TENGAN EMPLEADOS ASIGNADOS
SELECT B.*
FROM EMPLOYEES A
RIGHT JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
WHERE A.DEPARTMENT_ID IS NULL;

--NOTACION DE PRODUCTOS CARTESIANOS
SELECT B.*
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID (+) = B.DEPARTMENT_ID
AND A.DEPARTMENT_ID IS NULL;


--MOSTRAR TODOS LOS EMPLEADOS INDEPENDTIENEMENTE DE SI TIENEN UN DEPARTAMENTO ASIGNADO
-- Y MOSTRAR TODOS LOS DEPARTAMENTOS INDEPENDIENTEMENTE DE SI TIENEN EMPLEADOS ASIGNADOS
SELECT *
FROM EMPLOYEES A
FULL OUTER JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID;

-- MOSTRAR LOS EMPLEADOS QUE NO TIENEN DEPARTAMENTO
-- Y MOSTRAR LOS DEPARTAMENTOS QUE NO TIENEN EMPLEADOS
SELECT *
FROM EMPLOYEES A
FULL OUTER JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
WHERE A.DEPARTMENT_ID IS NULL OR B.DEPARTMENT_ID IS NULL;

-- CREATE OR REPLACE VIEW VW_EMPLOYEES AS 
CREATE MATERIALIZED VIEW MVW_EMPLOYEES AS
SELECT  A.FIRST_NAME || ' ' || A.LAST_NAME AS EMPLOYEE_NAME,
        B.FIRST_NAME || ' ' || B.LAST_NAME AS MANAGER_NAME,
        C.FIRST_NAME || ' ' || C.LAST_NAME AS GRAND_MANAGER_NAME,
        D.DEPARTMENT_NAME,
        E.FIRST_NAME || ' ' || E.LAST_NAME AS DEPARTMENT_MANAGER_NAME,
        F.CITY,
        F.STATE_PROVINCE,
        F.STREET_ADDRESS,
        G.COUNTRY_NAME,
        G.REGION_ID,
        H.REGION_NAME
FROM    EMPLOYEES A
LEFT JOIN EMPLOYEES B
ON A.MANAGER_ID = B.EMPLOYEE_ID
LEFT JOIN EMPLOYEES C
ON B.MANAGER_ID = C.EMPLOYEE_ID
LEFT JOIN DEPARTMENTS D
ON A.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN EMPLOYEES E
ON D.MANAGER_ID = E.EMPLOYEE_ID
LEFT JOIN LOCATIONS F
ON D.LOCATION_ID = F.LOCATION_ID
LEFT JOIN COUNTRIES G
ON F.COUNTRY_ID = G.COUNTRY_ID
LEFT JOIN REGIONS H
ON G.REGION_ID = H.REGION_ID
ORDER BY 3;

SELECT * FROM LOCATIONS;
SELECT * FROM COUNTRIES;
SELECT * FROM REGIONS;  












SELECT * FROM VW_EMPLOYEES; -- SE EJECUTA LA CONSULTA CADA VEZ QUE SE EJECUTA LA VISTA
SELECT * FROM MVW_EMPLOYEES; -- SE GUARDA LA INFOMACION AL CREAR LA VISTA MATERIALIZADA

BEGIN
    DBMS_MVIEW.REFRESH ('MVW_EMPLOYEES'); -- REFRESCA LA VISTA MATERIALIZADA
END;

SELECT COUNT(1) AS CANTIDAD_EMPLEADOS
FROM EMPLOYEES;

SELECT 4, 'HOLA', A.* FROM EMPLOYEES A;




SELECT SUM(SALARY) AS TOTAL_SALARIO
FROM EMPLOYEES;

SELECT AVG(SALARY) AS PROMEDIO_SALARIO
FROM EMPLOYEES;

SELECT MAX(SALARY) AS SALARIO_MAXIMO
FROM EMPLOYEES;

SELECT MIN(SALARY) AS SALARIO_MINIMO
FROM EMPLOYEES;


SELECT * 
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

SELECT *
FROM JOBS
WHERE JOB_ID = 'IT_PROG';